language: node_js
sudo: false
node_js:
  - "8"

branches:
  only:
    - master

cache:
  npm: true

install:
    - npm install

script:
    - npm run build

before_deploy:
  - zip -r snack-news-FE *
  - mkdir -p deploy
  - mv snack-news-FE.zip deploy/snack-news-FE.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: snack-news-deploy
    region: ap-northeast-2 # seoul
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo: snack-news/Snack-FE #Github
      branch: master

notifications:
  slack: opensourcekr:3wXZfw1QFGKrbPrNR99ZLR10