language: node_js
sudo: false
node_js:
  - "10"

cache:
  npm: true

install:
    - npm install

script:
    - npm run lint
    - npm run build

before_deploy:
  - zip -x node_modules/\* -r snack-news-FE *
  - mkdir -p deploy
  - mv snack-news-FE.zip deploy/snack-news-FE.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: snack-news-deploy
    region: ap-northeast-2 # seoul
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo: snack-news/Snack-FE #Github
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: snack-news-deploy
    key: snack-news-FE.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: snack-news-deploy # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: snack-news-FE # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: snack-news/Snack-FE #Github
      branch: master

notifications:
  slack: opensourcekr:3wXZfw1QFGKrbPrNR99ZLR10