/* eslint-disable max-lines */
export const resData: { data: News[] } = {
  data: [
    {
      createAt: '2019-12-29T21:38:29',
      modifiedAt: '2019-12-29T21:38:29',
      id: 137,
      title: '\uD83E\uDD1D LG유플러스와 토스가 인수 협상을 계속 진행 중',
      content:
        '[{"type":"paragraph","data":{"text":"✅ 개요"}},{"type":"paragraph","data":{"text":"1.LG유플러스는 전자결제사업부 매각을 위해 토스의 비바리퍼블리카와 협상을 계속 진행 중."}},{"type":"paragraph","data":{"text":"2.업계에 따르면, 양측의 가격 협상은 구체적인 범위를 언급할만한 수준까지 도달했다고 함."}},{"type":"paragraph","data":{"text":"3.처음에는 4000억원 정도였지만, LG유플러스가 가격을 양보하고 비바리퍼블리카는 3000억 초중반을 희망하고 있다고 함."}},{"type":"paragraph","data":{"text":"✅ 더 알아보기"}},{"type":"paragraph","data":{"text":"1.협상이 순조롭게 진행되고 있다고 하지만, 비바리퍼블리카가 가격인하를 좀더 요구하고 있는 상황."}},{"type":"paragraph","data":{"text":"2.협상이 계속 진행될 경우 조만간 본계약이 체결될 가능성이 높을 것으로 보임."}},{"type":"paragraph","data":{"text":"큰 일이 없으면 토스의 PG사업부 인수가 현실로 다가올 것으로 보이네요."}},{"type":"paragraph","data":{"text":"(여러분들은 이 소식에 대해 어떻게 생각하시나요?\uD83D\uDE4F)"}}]',
      link:
        'http://www.thebell.co.kr/free/content/ArticleView.asp?key=201910280100049790003100&svccode=00&page=1&sort=thebell_check_time',
      category: { id: 3, title: '핀테크' },
      topics: [{ id: 2, type: 'CORP', name: '비바리퍼블리카', image: '/logo/toss.svg' }],
      tags: [],
      publishAt: '2019-12-29T21:38:29',
    },
    {
      createAt: '2019-12-29T21:36:51',
      modifiedAt: '2019-12-29T21:36:51',
      id: 136,
      title: '\uD83D\uDCF1 중고폰 거래 플랫폼 ‘바른폰’과 토스가 제휴합니다',
      content:
        '[{"type":"paragraph","data":{"text":"✅ 개요"}},{"type":"paragraph","data":{"text":"1.토스의 비바리퍼블리카와 바른폰의 SK텔링크가 제휴."}},{"type":"paragraph","data":{"text":"2.‘바른폰’은 토스 앱과 연동해 파손폰, 불량폰, 장롱폰을 포함한 모든 중고 스마트폰의 온라인 시세 조회 서비스를 제공."}},{"type":"paragraph","data":{"text":"3.휴대폰 판매점을 직접 방문하지 않아도 중고 스마트폰의 기본적인 상태 감정 및 시세 파악이 가능."}},{"type":"paragraph","data":{"text":"토스가 다양한 서비스를 내놓고 있네요."}},{"type":"paragraph","data":{"text":"점점 플랫폼화 되어가고 있는 것 같습니다."}},{"type":"paragraph","data":{"text":"(유용했다면 좋아요!와 공유! 부탁드려요 \uD83D\uDE0A)"}}]',
      link: 'https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=138&aid=0002078761',
      category: { id: 3, title: '핀테크' },
      topics: [{ id: 2, type: 'CORP', name: '비바리퍼블리카', image: '/logo/toss.svg' }],
      tags: [],
      publishAt: '2019-12-29T21:36:51',
    },
    {
      createAt: '2019-12-29T21:35:03',
      modifiedAt: '2019-12-29T21:35:03',
      id: 135,
      title: '\uD83C\uDD95 토스가 새로운 행운퀴즈 가이드라인을 내놓았습니다.',
      content:
        '[{"type":"paragraph","data":{"text":"✅ 개요"}},{"type":"paragraph","data":{"text":"1.토스의 비바리퍼블리카가 \'행운퀴즈’ 운영에 대한 새 가이드라인을 도입함."}},{"type":"paragraph","data":{"text":"2.이유는 포털 실시간 검색에 미치는 영향을 최소화하려고."}},{"type":"paragraph","data":{"text":"(유용했다면 좋아요!와 공유! 부탁드려요 \uD83D\uDE0A)"}}]',
      link: 'https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=018&aid=0004502358',
      category: { id: 3, title: '핀테크' },
      topics: [{ id: 2, type: 'CORP', name: '비바리퍼블리카', image: '/logo/toss.svg' }],
      tags: [],
      publishAt: '2019-12-29T21:35:03',
    },
    {
      createAt: '2019-12-29T21:33:59',
      modifiedAt: '2019-12-29T21:33:59',
      id: 134,
      title: '\uD83C\uDFAB 야놀자가 자체 개발한 도심형 투어 상품을 내놓았습니다',
      content:
        '[{"type":"paragraph","data":{"text":"✅ 개요"}},{"type":"paragraph","data":{"text":"1.야놀자 계열사 레저큐가 자체 개발한 도심형 투어패스 ‘홍대 야놀자 패스’를 출시."}},{"type":"paragraph","data":{"text":"2.\'홍대 야놀자 패스\'는 홍대에 위치한 주요 놀거리와 식당 12곳을 할인가로 이용할 수 있는 모바일 티켓."}},{"type":"paragraph","data":{"text":"3.\'빅2\'권은 2곳, \'빅3\'권은 3곳을 자유롭게 이용할 수 있다고 함"}},{"type":"paragraph","data":{"text":"(여러분들은 이 소식에 대해 어떻게 생각하시나요?\uD83D\uDE4F)"}}]',
      link: 'http://www.sportsseoul.com/news/read/838986',
      category: { id: 1, title: 'O2O' },
      topics: [{ id: 4, type: 'CORP', name: '야놀자', image: '/logo/yanolja.svg' }],
      tags: [],
      publishAt: '2019-12-29T21:33:59',
    },
    {
      createAt: '2019-12-29T21:32:46',
      modifiedAt: '2019-12-29T21:32:46',
      id: 133,
      title: '\uD83C\uDD95 우아한형제들이 영상SNS ‘띠잉’을 출시했습니다',
      content:
        '[{"type":"paragraph","data":{"text":"✅ 띠잉이 뭐야?"}},{"type":"paragraph","data":{"text":"1.10초 이내의 짧은 동영상을 만들어 공유하는 ‘모바일 영상 놀이 플랫폼’."}},{"type":"paragraph","data":{"text":"2.서비스명은 영상을 찍을 때 나는 소리에서 착안했다고 함.(영상을 찍을 때는 ‘띠잉’이라는 소리가 난다고.)"}},{"type":"paragraph","data":{"text":"3.영상을 즐겨 이용하고 익숙해하는 Z세대와 함께하는 놀이 문화를 만들어가고자하는게 이번 서비스 출시 배경."}},{"type":"paragraph","data":{"text":"(점심시간에 화제거리로 삼고 싶으면 이 뉴스를 공유해보세요\uD83D\uDE0A)"}}]',
      link: 'https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=105&oid=293&aid=0000025400',
      category: { id: 1, title: 'O2O' },
      topics: [{ id: 1, type: 'CORP', name: '우아한형제들', image: '/logo/woowa.svg' }],
      tags: [],
      publishAt: '2019-12-29T21:32:46',
    },
    {
      createAt: '2019-12-29T19:20:40',
      modifiedAt: '2019-12-29T19:20:40',
      id: 129,
      title: '\uD83D\uDC40  새벽배송 이용 트렌드 1위는 마켓컬리가 차지했습니다.',
      content:
        '[{"type":"paragraph","data":{"text":"1.코바코 조사결과, 소비자들의 39.4%가 마켓컬리를 이용."}},{"type":"paragraph","data":{"text":" 2.쿠팡은 35.8%를 차지하며 2위, SSG닷컴(16.4%)은 3위를 차지."}},{"type":"paragraph","data":{"text":"3.한번이라도 이용한 새벽배송 브랜드는 마켓컬리가 59.2%로 1위를 차지. 쿠팡(56%)과 SSG닷컴(32.8%)이 2,3위를 차지."}},{"type":"paragraph","data":{"text":"4.소비자들이 새벽배송을 선택할 때 가장 큰 영향을 주는 매체는 TV광고(45.8%)."}},{"type":"paragraph","data":{"text":"5.새벽배송 이용 시 가장 중요하게 보는 요소는 ‘품질’(30.6%)이 1위. "}},{"type":"paragraph","data":{"text":"배송속도(19.2%)와 할인 및 프로모션(16%)이 2,3위를 차지."}},{"type":"paragraph","data":{"text":"아직 마켓컬리는 새벽배송의 강자로 있지만, 쿠팡의 추격이 정말 무섭습니다."}},{"type":"paragraph","data":{"text":"마켓컬리가 왕좌를 지킬 수 있을까요?"}}]',
      link: 'https://www.ajunews.com/view/20191220153240058',
      category: { id: 2, title: '커머스' },
      topics: [{ id: 12, type: 'CORP', name: '컬리', image: null }],
      tags: [],
      publishAt: '2019-12-29T19:20:40',
    },
    {
      createAt: '2019-12-29T19:19:31',
      modifiedAt: '2019-12-29T19:19:31',
      id: 128,
      title: '\uD83C\uDFE6 드디어 인터넷 전문 은행이 된 토스뱅크',
      content:
        '[{"type":"paragraph","data":{"text":"1. 16일 금융위원회는 토스뱅크에 인터넷 전문은행 예비인가를 내주기로 결정"}},{"type":"paragraph","data":{"text":"2. 카카오 뱅크와 케이뱅크를 이어 3번째 전문 은행"}},{"type":"paragraph","data":{"text":"3. 내년 1월 중 본인가를 받게 되며 이후 6개월 이내에 영업을 시작"}},{"type":"paragraph","data":{"text":"토스는 1,600만 명의 가입자 데이터를 기반으로<b>,&nbsp;</b>중신용 개인 고객과 소상공인에 집중하는 ‘챌린지 뱅크’ 모델을 제시했는데요."}},{"type":"paragraph","data":{"text":"어떤 모습을 보여줄지 기대가 됩니다!"}}]',
      link: 'https://blog.toss.im/2019/12/16/newsroom/press-release/toss-internet-only-bank/',
      category: { id: 3, title: '핀테크' },
      topics: [{ id: 2, type: 'CORP', name: '비바리퍼블리카', image: '/logo/toss.svg' }],
      tags: [],
      publishAt: '2019-12-29T19:19:31',
    },
    {
      createAt: '2019-12-29T19:18:31',
      modifiedAt: '2019-12-29T19:18:31',
      id: 127,
      title: '\uD83D\uDC40 배민이 저격한 쿠팡의 쿠팡이츠는 현재 어떨까?',
      content:
        '[{"type":"paragraph","data":{"text":"1.쿠팡이츠의 현재 점유율은 업계 9위 정도."}},{"type":"paragraph","data":{"text":"2.광폭행보를 벌였던 초반 기세와 달리 최근 기세는 잠잠한 것으로 보임. "}},{"type":"paragraph","data":{"text":"3.베타테스트를 시작한 지 7개월 차에 접어들었지만, 정식 런칭 시기는 미정. "}},{"type":"paragraph","data":{"text":"현재 입점 업체 수도 적고 수수료도 경쟁 업체보다 비싼 상태. "}},{"type":"paragraph","data":{"text":"쿠팡이츠가 배민,요기요,배달통 연합군에 맞서기 위해선 파격적인 카드가 필요할 것 같습니다."}},{"type":"paragraph","data":{"text":"위메프오 등 치고 나오는 배달 서비스도 있는데, 쿠팡이츠는 앞으로 어떻게 될까요?"}}]',
      link: 'https://www.wikitree.co.kr/main/news_view.php?id=490194',
      category: { id: 2, title: '커머스' },
      topics: [{ id: 3, type: 'CORP', name: '쿠팡', image: '/logo/coupang.svg' }],
      tags: [],
      publishAt: '2019-12-29T19:18:31',
    },
    {
      createAt: '2019-12-29T19:16:50',
      modifiedAt: '2019-12-29T19:16:50',
      id: 126,
      title: '\uD83D\uDC40 쿠팡,티몬,위메프는 어떤 길을 가고 있을까?',
      content:
        '[{"type":"paragraph","data":{"text":"1.비슷한 시기에 소셜커머스로 시작한 쿠팡, 위메프, 티몬은 각자 다른길을 걷고 있음."}},{"type":"paragraph","data":{"text":"2.위메프는 최근 I1200억원을 투자받아 올 하반기에 3700억원 규모의 투자를 유치. "}},{"type":"paragraph","data":{"text":"3.투자금 대부분은 인력 충원과 파트너사 확보, 시스템 개선에 투자한다고 함."}},{"type":"paragraph","data":{"text":"4.쿠팡은 소프트뱅크가 2015년과 2018년, 2차례에 걸쳐 30억 달러를 투자했지만 현재로서 내년 상반기엔 이 금액이 모두 소진될 것으로 전망. "}},{"type":"paragraph","data":{"text":"5.쿠팡의 대안으로 거론되는 썰 중 하나가 나스닥 상장."}},{"type":"paragraph","data":{"text":"6.티몬의 경우 매각설이 지속적으로 나오는 중. "}},{"type":"paragraph","data":{"text":"7.최근 롯데의 티몬 인수설이 나왔지만 양사 모두 부인. "}}]',
      link: 'http://www.newsis.com/view/?id=NISX20191213_0000860155',
      category: { id: 2, title: '커머스' },
      topics: [{ id: 22, type: 'CORP', name: '시장동향', image: null }],
      tags: [],
      publishAt: '2019-12-29T19:16:50',
    },
    {
      createAt: '2019-12-29T19:16:09',
      modifiedAt: '2019-12-29T19:16:09',
      id: 125,
      title: '\uD83C\uDF7D 우리는 늘 변화하며 생존해 나갈 것입니다.',
      content:
        '[{"type":"paragraph","data":{"text":"[인수에 대해]"}},{"type":"paragraph","data":{"text":"1. 딜리버리 히어로와 주식 맞교환 딜리버리 히어로 경영진 중 최대 주주가 됨<b>.</b>"}},{"type":"paragraph","data":{"text":"2. 인수로 김봉진 대표는 딜리버리 히어로 글로벌 3인 최고위원회 구성원으로 합류."}},{"type":"paragraph","data":{"text":"3. 아시아 시장의 1위가 됨 (중국제외)= 독일 상장회사에 인수되었기에 배달의민족도 상장 (에디터의 해석)"}},{"type":"paragraph","data":{"text":"4. 배달의민족의 경영진은 아시아 주요 지역을 경영(태국, 대만, 싱가포르, 홍콩, 말레이시아, 필리핀, 한국, 베트남)과 자사 경영으로 나눠짐<b>.</b>"}},{"type":"paragraph","data":{"text":"[배달의 민족에 대해]"}},{"type":"paragraph","data":{"text":"1. 배달의 민족은 김범준 부사장이 새로운 CEO 선임<b>.</b>"}},{"type":"paragraph","data":{"text":"2. 현 체재를 유지하지만 이후 경영진의 방식에 따라 달라질 수 있음."}},{"type":"paragraph","data":{"text":"3. 요기요와 통합하지 않으며 서로 경쟁 구도로 가지 않을 예정."}},{"type":"paragraph","data":{"text":"4. 현 사업은 유지되며 국내 서비스를 해외에 전파할 예정."}},{"type":"paragraph","data":{"text":"이번 인수합병에 대한 김봉진 대표님이 쓰신 사내메일의 내용을 요약했으며, 원본은 아래 링크에서 확인 하실 수 있습니다."}}]',
      link: 'https://byline.network/2019/12/13-71/',
      category: { id: 1, title: 'O2O' },
      topics: [{ id: 1, type: 'CORP', name: '우아한형제들', image: '/logo/woowa.svg' }],
      tags: [],
      publishAt: '2019-12-29T19:16:09',
    },
    {
      createAt: '2019-12-29T19:15:10',
      modifiedAt: '2019-12-29T19:15:10',
      id: 124,
      title:
        "\uD83D\uDC40 우아한형제들 김봉진 대표는 어떻게 스타트업들 사이에서 'CEO 벤치마크'로 불렸을까? ",
      content:
        '[{"type":"paragraph","data":{"text":"1.사장님이 잘 쉬어야 한다. 쉬어야 새로운 세상이 보인다."}},{"type":"paragraph","data":{"text":"2.사장님은 고민하고, 철학을 하는 철인이 되어야 한다."}},{"type":"paragraph","data":{"text":"3.직원이 와야한다? 아니다. 사장님이 가야 한다."}},{"type":"paragraph","data":{"text":"4.회사는 자율주행차. 규율과 자율의 밸런스가 중요하다."}},{"type":"paragraph","data":{"text":"5.사장님이 갑자기 뒤에 나타났을 때 행동을 보면 그 회사를 알 수 있다. "}}]',
      link: 'https://1boon.kakao.com/ttimes/5df3aa7ba895113ccdb11002',
      category: { id: 1, title: 'O2O' },
      topics: [{ id: 1, type: 'CORP', name: '우아한형제들', image: '/logo/woowa.svg' }],
      tags: [],
      publishAt: '2019-12-29T19:15:10',
    },
    {
      createAt: '2019-12-29T19:14:09',
      modifiedAt: '2019-12-29T19:14:09',
      id: 123,
      title: '\uD83D\uDC40 토스뱅크가 진짜 나올 수 있을까요?',
      content:
        '[{"type":"paragraph","data":{"text":"1.금감원은 12/15일까지 2박 3일간 토스뱅크와 소소스마트뱅크에 대한 심사를 진행."}},{"type":"paragraph","data":{"text":"2.현재 최대 2곳에 예비 인가를 내줄 것으로 밝혀 토스뱅크의 인가 가능성은 더 높아지는 분위기."}},{"type":"paragraph","data":{"text":"3.이번에는 자본조달력 확보를 위해 주주구성에 변화를 주어,토스가 34%, KEB하나은행 10%, SC제일은행6.67% 등을 포함시킴."}},{"type":"paragraph","data":{"text":"4.중소기업중앙회(10%)와 웰컴저축은행(5.0%)을 주주로 참여시킨 점도 ‘포용성’ 항목에서 점수를 받을 것으로 보임."}},{"type":"paragraph","data":{"text":"이미 혁신성은 인정받았지만, 안정성이 부족해 탈락했던 토스뱅크."}},{"type":"paragraph","data":{"text":"재수 과연 성공할 수 있을까요? 기대가 됩니다."}}]',
      link: 'http://www.sporbiz.co.kr/news/articleView.html?idxno=400115',
      category: { id: 3, title: '핀테크' },
      topics: [{ id: 2, type: 'CORP', name: '비바리퍼블리카', image: '/logo/toss.svg' }],
      tags: [],
      publishAt: '2019-12-29T19:14:09',
    },
    {
      createAt: '2019-12-29T19:13:25',
      modifiedAt: '2019-12-29T19:13:25',
      id: 122,
      title: '\uD83D\uDC40 유니콘 위메프가 공격적으로 MD채용에 나섰습니다.',
      content:
        '[{"type":"paragraph","data":{"text":"1.12/12일 부터 경력 공채를 시작으로 2020년까지 1000명의 MD를 신규 채용할 계획이라고 밝힘."}},{"type":"paragraph","data":{"text":"2.위메프는 매년 MD 공채를 꾸준히 진행해왔지만, 네 자릿수 채용을 예고한 것은 이번이 처음."}},{"type":"paragraph","data":{"text":"3.올해 하반기에 총 3700억원을 확보한 위메프는 파트너사 확보와 인력충원에 총력을 기울이는 중."}},{"type":"paragraph","data":{"text":"위메프가 MD모집에 사활을 걸었습니다.&nbsp; 4자리 수 대규모 채용은 정말 보기드문 규모이네요."}},{"type":"paragraph","data":{"text":"위메프가 얼마나 성장할지 기대가 됩니다."}},{"type":"paragraph","data":{"text":"이제 슬슬 커머스 전쟁에 끝이 보이게 될까요?"}}]',
      link: 'http://www.getnews.co.kr/view.php?ud=20191212150748730741d0c69529_16',
      category: { id: 2, title: '커머스' },
      topics: [{ id: 5, type: 'CORP', name: '위메프', image: '/logo/wemakeprice.svg' }],
      tags: [],
      publishAt: '2019-12-29T19:13:25',
    },
    {
      createAt: '2019-12-29T19:12:17',
      modifiedAt: '2019-12-29T19:12:17',
      id: 121,
      title: '\uD83D\uDC40 11번째 유니콘이 나왔습니다.',
      content:
        '[{"type":"paragraph","data":{"text":"1.면역치료제 제조업체 에이프로젠이 CB인사이트 기준 국내 11번째 유니콘으로 등재됨."}},{"type":"paragraph","data":{"text":"2.에이프로젠은 김재섭 대표가 카이스트 교수로 재직할 당시 제넥셀을 설립, 2016년 에이프로젠을 인수하면서 시작됨. "}},{"type":"paragraph","data":{"text":"3.현재 자기면역질환 치료제 등을 기술 이전 받아 일본 니치이코제약과 판권계약을 통해 판매하는 중."}},{"type":"paragraph","data":{"text":"4.이제 우리나라의 국가별 유니콘 기업 순위는 미국(210개), 중국(102개), 영국(22개), 인도(18개)에 이어 독일과 함께 공동 5위가 됨."}},{"type":"paragraph","data":{"text":"이번 유니콘 \'에이프로젠\'은 특별한데요."}},{"type":"paragraph","data":{"text":"이때까지의 유니콘은 주로 IT 분야에 집중된 반면 에이프로젠은 생명공학 기업입니다. "}},{"type":"paragraph","data":{"text":"한국의 유니콘 업종이 좀 더 다양해지고 있는 것 같습니다."}}]',
      link: 'https://www.venturesquare.net/798227',
      category: { id: 5, title: 'IT' },
      topics: [{ id: 22, type: 'CORP', name: '시장동향', image: null }],
      tags: [],
      publishAt: '2019-12-29T19:12:17',
    },
    {
      createAt: '2019-12-29T19:07:32',
      modifiedAt: '2019-12-29T19:07:32',
      id: 120,
      title:
        '\uD83D\uDC40 토스가 기존 타겟층이 아니었던 30·40세대 사용자층을 빠르게 흡수하고 있습니다.',
      content:
        '[{"type":"paragraph","data":{"text":"1.토스는 올해 11월 기준, 1월 대비 가장 큰 폭의 3040세대 사용자층을 확보함."}},{"type":"paragraph","data":{"text":"2.30대는 1월(91만명)보다 132만명 증가, 40대는 1월(71만명)보다 116만명 증가."}},{"type":"paragraph","data":{"text":"3.현재 토스는 뱅킹 앱 중 신규 유입자 수, 월별 사용자 수, 10·20세대 사용자 수 모두 1위를 차지."}},{"type":"paragraph","data":{"text":"4.30대와 40대에서는 2위를 차지, 50대에서는 3위로 떨어짐."}},{"type":"paragraph","data":{"text":"토스가 메인 타겟층에서 더 확장하고 있는 모습을 보여주고 있네요. 성장세가 무섭습니다."}}]',
      link: 'http://www.kbanker.co.kr/news/articleView.html?idxno=88412',
      category: { id: 3, title: '핀테크' },
      topics: [{ id: 2, type: 'CORP', name: '비바리퍼블리카', image: '/logo/toss.svg' }],
      tags: [],
      publishAt: '2019-12-29T19:07:32',
    },
    {
      createAt: '2019-12-29T19:05:54',
      modifiedAt: '2019-12-29T19:05:54',
      id: 119,
      title: '\uD83D\uDC40 쿠팡에 새로 입점한 판매자 수가 작년보다 100% 늘었습니다. ',
      content:
        '[{"type":"paragraph","data":{"text":"1.쿠팡 마켓플레이스의 판매자는 폭발적으로 늘고 있음."}},{"type":"paragraph","data":{"text":"2.MD 없이도 공정하게 상위 노출을 확보할 수 있는 시스템, 최저수준의 판매수수료 등이 긍정적으로 작용."}},{"type":"paragraph","data":{"text":"3.최근에는 업계 최초로 모바일로 가능한 입점 시스템을 선보이기도 함."}},{"type":"paragraph","data":{"text":"쿠팡에 판매자들이 끊임없이 모여들고 있습니다."}},{"type":"paragraph","data":{"text":"소비자 사이드에서도 끊임없는 혁신을 추구하는 쿠팡이지만, 판매자 사이드도 역시 놓치지 않네요."}}]',
      link: 'http://www.fnnews.com/news/201912271751038234',
      category: { id: 2, title: '커머스' },
      topics: [{ id: 3, type: 'CORP', name: '쿠팡', image: '/logo/coupang.svg' }],
      tags: [],
      publishAt: '2019-12-29T19:05:54',
    },
    {
      createAt: '2019-12-29T19:03:42',
      modifiedAt: '2019-12-29T19:03:42',
      id: 118,
      title: '\uD83D\uDCC8 베트남에서 음식 배달 서비스 시장이 폭풍 성장중입니다. ',
      content:
        '[{"type":"paragraph","data":{"text":"1.코트라에 따르면 베트남의 온라인 배달 시장 규모는 2019년 기준 2억 700만 달러."}},{"type":"paragraph","data":{"text":"2.향후 5년간 연평균 성장률은 19.5%로 예상되며, 2024년에는 5억 500만 달러 규모까지 이를 것으로 예상."}},{"type":"paragraph","data":{"text":"3.2013년에는 서비스 이용비율이 2.5%였으나 2018년에는 5%까지 2배로 증가. "}},{"type":"paragraph","data":{"text":"4.본격적으로 활성화된 것은 2018년 하반기 이후부터이므로, 향후 배달 서비스 이용률은 더 높게 성장할 것으로 예상됨."}},{"type":"paragraph","data":{"text":"5.주요 시장 경쟁자는 GO-Viet, Grab Food, Vietnamm, Foody 등이 존재."}}]',
      link: 'http://www.dailybizon.com/news/articleView.html?idxno=15245',
      category: { id: 1, title: 'O2O' },
      topics: [{ id: 22, type: 'CORP', name: '시장동향', image: null }],
      tags: [],
      publishAt: '2019-12-29T19:03:42',
    },
    {
      createAt: '2019-12-29T19:02:01',
      modifiedAt: '2019-12-29T19:02:01',
      id: 117,
      title: '\uD83D\uDC40 지난 10년간 가장 돈을 많이 쓴, 다운로드를 많이 한 앱은 어디일까요?',
      content:
        '[{"type":"paragraph","data":{"text":"1.2010년대에 \\u001d가장 많은 다운로드를 기록한 앱 TOP 10 중 7개는 메신저,SNS 앱. "}},{"type":"paragraph","data":{"text":"2.1위 ~ 4위까지는 페이스북, 페이스북 메신저, 왓츠앱 메신저, 인스타그램이 차지."}},{"type":"paragraph","data":{"text":"3.가장 많이 돈을 쓴 앱은 넷플릭스가 1위, 틴더가 2위, 판도라 뮤직이 3위를 차지. "}},{"type":"paragraph","data":{"text":"4.지난 10년간 모바일 시장은 매년 소비자 지출 15% 이상 늘어났다고 함. "}},{"type":"paragraph","data":{"text":"모바일 시장 성장은 내년에도 계속 될 것 같습니다. 대단하네요."}},{"type":"paragraph","data":{"text":"(이 뉴스가 유용할 친구에게 이 뉴스를 공유해보세요\uD83D\uDE0A)"}}]',
      link: 'https://www.venturesquare.net/799369',
      category: { id: 5, title: 'IT' },
      topics: [{ id: 22, type: 'CORP', name: '시장동향', image: null }],
      tags: [],
      publishAt: '2019-12-29T19:02:01',
    },
  ],
};
